blog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/',
         views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<slug:post_slug>/share/',
         views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

config/urls.py
from django.contrib import admin
from django.urls import include ,path
from django.contrib.sitemaps.views import sitemap
from django.shortcuts import redirect

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

def index_page(request):
    return redirect('blog/')


urlpatterns = [
    path('', index_page),
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.shortcuts import reverse

from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset() \
                          .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

class Comment(models.Model): 
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80) 
    email = models.EmailField() 
    body = models.TextField() 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=True) 
 
    class Meta: 
        ordering = ('created',) 
 
    def __str__(self): 
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment
 
 
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25,
                           widget=forms.TextInput(
                               attrs={
                                   'class': 'form-control',
                               }
                           ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
            }
        ))
    to = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
            }
        ))
    comments = forms.CharField(required=False,
                               widget=forms.Textarea(
                                   attrs={
                                       'class': 'form-control p-2',
                                   }
                               ))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control '}),
            'email': forms.EmailInput(attrs={'class': 'form-control '}),
            'body': forms.Textarea(attrs={'class': 'form-control '}),
        }

blog/views.py
from django.db.models import Count
from django.views.generic import ListView
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage,\
    PageNotAnInteger
from django.shortcuts import render, get_object_or_404

from taggit.models import Tag

from .forms import EmailPostForm, CommentForm
from .models import Post, Comment


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                  .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags', '-publish')[:3]
    
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_share(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(
                cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(
                post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/post/list.html',
                  {'tag': tag,
                   'page': page,
                   'posts': posts})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
  </head>
  <body class="">
    {% include "blog/partials/navbar.html" %}
    <main id="content" class="container py-3">
      {% block content %} {% endblock %}
    </main>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js"
      integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js"
      integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9"
      crossorigin="anonymous"
    ></script>
    <script>
      $(document).ready(function() {
        $("body").bootstrapMaterialDesign();
      });
    </script>
  </body>
</html>

blog/templates/blog/partials/navbar.html
<nav class="navbar navbar-light bg-white border">
  <a class="navbar-brand" href="/blog/">
    <img
      src="https://cdn.onlinewebfonts.com/svg/img_198846.png"
      alt=""
      class="icon"
    />
    <span>
      Bloggy
    </span>
  </a>

  <ul class="d-flex list-unstyled">
    <li class="nav-item">
      <a class="nav-link" href="/blog/">
        <img
          src="http://cdn.onlinewebfonts.com/svg/img_387447.png"
          alt=""
          class="icon"
        />
        <span class="sr-only">(current)</span></a
      >
    </li>
    <li class="nav-item">
      <a href="{% url 'blog:post_feed' %}" class="nav-link">
        <img src="http://simpleicon.com/wp-content/uploads/rss.svg" alt="" class="icon">
      </a>
    </li>
  </ul>
</nav>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<h1 class="text-dark text-center">{{ post.title | title }}</h1>
<p class="text-secondary text-center">
  Published {{ post.publish }} by {{ post.author }}
</p>
<div class="bg-white p-3">
  <p class="article-text">
    {{ post.body|markdown }}
  </p>
</div>

<br />
<br />

<div class="similar_posts">
    <h6 class="text-dark text-center">Read More Like This Article</h6>
    <div class="row">
      {% for post in similar_posts %}
      <div class="card p-3 mx-2 col">
        <h6 class="text-primary text-capitalize">
              {{ post.title }}
            </h6>
            <small class="text-secondary"> @{{ post.author }}</small>
        <div class="py-4">
          <small class="card-text">
            {{ post.body|markdown|truncatewords_html:10 }}
          </small>
        </div>
        <div class="row">
          <div class="col-4">
            <a href="{{ post.get_absolute_url }}" class="btn btn-outline-primary btn-sm">
              Read
            </a>
          </div>
          <div class="col-8 text-right">
            <small class="text-secondary">{{ post.publish|date:"F Y" }}</small>
          </div>
        </div>
        
      </div>
      {% endfor %}
    </div>
  </div>

<br />
<br />

<div class="actions px-3">
  {% with comments.count as total_comments %}
  <span class="text-secondary">
    {{ total_comments }} comment{{ total_comments | pluralize }}
  </span>
  {% endwith %}
  <a
    class="btn btn-outline-primary mx-3"
    href="{% url 'blog:post_share' post.slug %}"
  >
    Share By Email
  </a>
</div>
<br />

{% for comment in comments %}
<div class="card p-3 rounded">
  <div class="d-flex align-items-center">
    <img
      src="https://png.pngtree.com/svg/20161021/de74bae88b.png"
      alt=""
      class="avatar"
    />
    <div>
      <h6 class="text-primary m-0">
        {{ comment.name | title }}
      </h6>
      <small class="text-secondary">
        {{ comment.created }}
      </small>
    </div>
  </div>

  <p>
    {{ comment.body | linebreaks }}
  </p>
</div>
{% empty %}
<div class="card p-3">
  <p>There are no comments yet.</p>
</div>
{% endfor %}
<br />
<br />

<div class="card p-3 my-3">
  {% if new_comment %}
  <h2>Your comment has been added.</h2>
  {% else %}
  <h4 class="text-primary">Add a new comment</h4>
  <form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p>
      <input
        class="btn btn-outline-primary"
        type="submit"
        value="Add comment"
      />
    </p>
  </form>
  {% endif %}
</div>
<br />
<br />
<br />
<br />
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Bloggy{% endblock %}

{% block content %}
{% if tag %}
  <h3 class="text-secondary">Posts tagged with "{{ tag.name }}"</h3>
{% endif %}

{% for post in posts %}
<div class="card post my-3 rounded">
  <div class="card-body">
    <div class="row">
      <div class="col-8">
        <h4 class="text-primary text-capitalize">
          {{ post.title }}
        </h4>
        {% for tag in post.tags.all %}
        <a class="badge text-secondary badge-light"
           href="{% url 'blog:post_list_by_tag' tag.slug %}">
          #{{ tag.name }}
        </a>
        {% endfor %}
      </div>
      <div class="col">
          <h6 class="text-secondary text-right"> @{{ post.author }}</h6>
      </div>
    </div>
    <div class="pb-4">
      <p class="card-text">
        {{ post.body|markdown|truncatewords_html:17 }}
      </p>
    </div>
    <div class="row">
      <div class="col">
        <a href="{{ post.get_absolute_url }}" class="btn btn-outline-primary btn-sm">
          Read
        </a>
      </div>
      <div class="col text-right">
          <div class="text-secondary">{{ post.publish }}</div>
        </div>
    </div>
    
  </div>
</div>
{% endfor %}

{% include "pagination.html" with page=posts %}

{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    <div class="bg-white p-4 w-50 mx-auto rounded border">
        {% if sent %}
        <h4 class="pb-3 text-primary"> E-mail successfully sent</h4>
        <div class="alert alert-success"> 
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.            
        </div>
        <a class="btn btn-primary" href="/blog/">
            Back
        </a>
        {% else %}
        <h3 class="text-primary pb-3">Share "{{ post.title }}" by e-mail</h3>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail" class="btn btn-primary">
        </form>
    </div>
  {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="text-center">
  <div class="step-links">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}" class="mx-3">
        <img src="https://png.pngtree.com/svg/20170523/d62342689e.svg" alt="" class="prev-btn">      
    </a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}" class="mx-3">
      <img src="https://png.pngtree.com/svg/20170523/d62342689e.svg" alt="" class="next-btn">
    </a>
    {% endif %}
  </div>
</div>